name: Publish to crates.io

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Update version in Cargo.toml
        run: |
          # Remove 'v' prefix if present in the tag
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          # Update version in Cargo.toml
          sed -i "s/^version = .*/version = \"${VERSION}\"/" Cargo.toml

      - name: Run tests
        run: cargo test --all-features

      - name: Publish to crates.io
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
