---
name: Publish to crates.io

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Verify tag matches Cargo.toml version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          CARGO_VERSION=$(cargo metadata --no-deps --format-version 1 \
              | jq -r '.packages[0].version')

          if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
            printf "❌ Tag version (%s) doesn't match Cargo.toml version (%s)\n" \
                "$TAG_VERSION" "$CARGO_VERSION"
            exit 1
          fi

          echo "✅ Tag version matches Cargo.toml version: $TAG_VERSION"

      - name: Run tests
        run: cargo test --all-features

      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_TOKEN }}
