name: Publish to crates.io

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Verify tag matches Cargo.toml version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          CARGO_VERSION=$(grep -m1 '^version' Cargo.toml | cut -d'"' -f2)

          if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
            echo "❌ Tag version ($TAG_VERSION) doesn't match Cargo.toml version ($CARGO_VERSION)"
            exit 1
          fi

          echo "✅ Tag version matches Cargo.toml version: $TAG_VERSION"

      - name: Run tests
        run: cargo test --all-features

      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CRATES_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          body: |
            ## 📦 Published to crates.io

            This release is now available on [crates.io](https://crates.io/crates/liiga_teletext/${{ github.ref_name }})

            ### Install or Update
            ```bash
            cargo install liiga_teletext
            ```
